#Charles Ajjan, cmp131, Week 4, Lab 1, box office report, started on 09/10/2026
Movie=input("Enter Movie Name")
Movie=("Coyote VS. ACME")
Adult=int(input("Enter Amount of Adult Tickets Sold"))
Child=int(input("Enter Amount of Child Tickets Sold"))
gross=int(Adult*10+Child*6)
net=int(float(gross*0.2))
Amount=input(float(4582-916.4))
print("Enter Movie Name:",Movie)
print ("Adult")
print("Child")
print(gross)
print(net)
print(Amount)