#Charles Ajjan, cmp131, Week 4, Lab 1, box office report, started on 09/10/2026
Movie=input("Enter Movie Name")
Adult=int(input("Enter Amount of Adult Tickets Sold"))
Child=int(input("Enter Amount of Child Tickets Sold"))
gross=int(Adult*10+Child*6)
net=int(float(gross*0.2))
Amount=int(float(gross-net))
Distributor=int(float(Amount-net*0.8))
print("Movie Name:",Movie)
print ("Adult",Adult)
print("Child",Child)
print("gross",gross)
print("net",net)
print("Amount",Amount)
print("Distributor",Distributor)