#Charles Ajjan, cmp131, Week 4, Lab 1, box office report, started on 09/10/2026
Movie=input("Enter Movie Name")
Adult=int(input("Enter Amount of Adult Tickets Sold"))
Child=int(input("Enter Amount of Child Tickets Sold"))
gross=float(Adult*10+Child*6)
net=(float(gross*0.20))
Amount=(float(gross-net))
Distributor=(float(Amount-net*0.80))
print("Movie Name:",Movie)
print (f"Adult tickets sold",Adult)
print(f"Child tickets sold",Child)
print(f"gross",gross)
print(f"net",net)
print(f"Amount",Amount)
print(f"Distributor",Distributor)